module.exports = {
  MONGO: process.env.MONGO,
  PORT: process.env.PORT,
  JWT_SECRET: process.env.JWT_SECRET,
  ACCESS_JWT_EXPIRATION_TIME: process.env.ACCESS_JWT_EXPIRATION_TIME,
  REFRESH_JWT_EXPIRATION_TIME: process.env.REFRESH_JWT_EXPIRATION_TIME,
  MONGO_STORE_SECRET: process.env.MONGO_STORE_SECRET,
  HOSTNAME: process.env.HOSTNAME,
  ALLOW_ORIGIN: process.env.ALLOW_ORIGIN
};
